version: '3.5'

services:
  node1.local:
    image: ex_cluster:latest
    environment:
      - RELEASE_COOKIE=secret-cookie
      - SERVICE_NAME=ex_cluster
      - SECRET_KEY_BASE=foo
      - PORT=4001
      - APP_HOST=localhost
      - NODE_NAME=node1
      - HOSTNAME=node1.local
      - LANG=C.UTF-8
    ports:
      - "4001:4001"
  node2.local:
    image: ex_cluster:latest
    environment:
      - RELEASE_COOKIE=secret-cookie
      - SERVICE_NAME=ex_cluster
      - SECRET_KEY_BASE=foo
      - PORT=4002
      - APP_HOST=localhost
      - NODE_NAME=node2
      - HOSTNAME=node2.local
      - LANG=C.UTF-8
    ports:
      - "4002:4002"
  node3.local:
    image: ex_cluster:latest
    environment:
      - RELEASE_COOKIE=secret-cookie
      - SERVICE_NAME=ex_cluster
      - SECRET_KEY_BASE=foo
      - PORT=4003
      - APP_HOST=localhost
      - NODE_NAME=node3
      - HOSTNAME=node3.local
      - LANG=C.UTF-8
    ports:
      - "4003:4003"
