version: '3.5'

services:
  node1.local:
    image: ex_cluster:latest
    environment:
      - RELEASE_COOKIE=secret-cookie
      - SERVICE_NAME=ex_cluster
      - SECRET_KEY_BASE=foo
      - PORT=80
      - APP_HOST=localhost
      - NODE_NAME=node1
      - HOSTNAME=node1.local
      - LANG=C.UTF-8
      - EPMDLESS_DIST_PORT=17012
    ports:
      - "4001:80"
  node2.local:
    image: ex_cluster:latest
    environment:
      - RELEASE_COOKIE=secret-cookie
      - SERVICE_NAME=ex_cluster
      - SECRET_KEY_BASE=foo
      - PORT=80
      - APP_HOST=localhost
      - NODE_NAME=node2
      - HOSTNAME=node2.local
      - LANG=C.UTF-8
      - EPMDLESS_DIST_PORT=17012
    ports:
      - "4002:80"
  node3.local:
    image: ex_cluster:latest
    environment:
      - RELEASE_COOKIE=secret-cookie
      - SERVICE_NAME=ex_cluster
      - SECRET_KEY_BASE=foo
      - PORT=80
      - APP_HOST=localhost
      - NODE_NAME=node3
      - HOSTNAME=node3.local
      - LANG=C.UTF-8
      - EPMDLESS_DIST_PORT=17012
    ports:
      - "4003:80"
